---
title: "Analyzing Consumer Networks"
date: 2017-05-02
categories: ["Consumer Analysis"]
tags: ["network analysis", "consumer reviews", "visualization"]
draft: true
output: md_document

---

## Purpose

<INSERT STUFF ABOUT PURPOSE>

## Background

<INSERT STUFF ABOUT BACKGROUND>

## Workflow

<INSERT STUFF ABOUT WORKFLOW>

```{r setup, include = FALSE}

## Load packages

# Data loading
library(jsonlite)
library(tidyjson)

# Data manipulation
library(tidyverse)

# Data visualization
library(ggthemes)
library(extrafont)
library(scales)
library(igraph)
library(network) 
library(sna)
library(ndtv)

## Set plot theme
theme_set(
  theme_bw(base_family = 'Arial', base_size = 12) +
    theme(
      plot.title = element_text(face = 'bold', hjust = 0),
      text = element_text(colour = '#4e5c65'),
      panel.background = element_rect('#ffffff'),
      strip.background = element_rect('#ffffff', colour = 'white'),
      plot.background = element_rect('#ffffff'),
      panel.border = element_rect(colour = '#ffffff'),
      panel.grid.major.x = element_blank(),
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank(),
      legend.background = element_rect('#ffffff'),
      legend.title = element_blank(),
      legend.position = 'right',
      legend.direction = 'vertical',
      legend.key = element_blank(),
      strip.text = element_text(face = 'bold', size = 10),
      axis.text = element_text(face = 'bold', size = 9),
      axis.title = element_blank(),
      axis.ticks = element_blank()
    )
)

```

```{r, pull-data}

## Read in json file
network.data <- jsonlite::fromJSON(txt = '../user_networks.json', 
                         simplifyDataFrame = TRUE)

# Remove '@' from reviewer names 
network.data$author <- gsub('@', '', network.data$author)

# Replace character(0) comment-author elements
network.data <- network.data %>% 
  mutate(comment_authors = map2(author, `comment-authors`, function(a, ca) { ifelse(nrow(data.frame(ca)) == 0, a, return(ca) )}))

## Replicate author names based on the number of commenters

# Find the number of commenters
network.data <- network.data %>% 
  mutate(n_comment_authors = map_dbl(`comment_authors`, function(i) length(i)))

# Remove reviews with less than 5 comments
network.data <- network.data[network.data$n_comment_authors > 5, ]

# Number of reviews by individual
n_reviews <- data.frame(table(network.data$author))

# Replicate review data based on the number of commenters
network.data_expanded <- data.frame('review_author' = rep(network.data$author, network.data$n_comment_authors), 
                           'comment_author' = unlist(network.data$comment_authors),
                           'product' = rep(network.data$product, network.data$n_comment_authors),
                           'brand' = rep(network.data$brand, network.data$n_comment_authors),
                           'type' = rep(network.data$type, network.data$n_comment_authors))

# Remove '@' from commenter names
network.data_expanded$comment_author <- gsub('@', '', network.data_expanded$comment_author)

# Number of comments
n_comments <- data.frame(table(network.data_expanded$comment_author))
names(n_comments) <- c('Var1', 'comments')
```

```{r, plot-initial}

# Build column of review and comment authors
authors_total <- rbind(data.frame('auth' = network.data_expanded$review_author),
                       data.frame('auth' = network.data_expanded$comment_author))

authors_total <- data.frame('auth' = unique(gsub('@', '', authors_total$auth)))

# Build node data
nodes <- data.frame('id' = paste0('c', seq(from = 1, to = nrow(authors_total))),
                    'name' = authors_total,
                    'n_reviews' = left_join(left_join(authors_total, 
                                            n_reviews,
                                            by = c('auth' = 'Var1')),
                                            n_comments,
                                            by = c('auth' = 'Var1'))) %>% 
  select(-n_reviews.auth) %>%
  mutate(t_interactions = ifelse(is.na(n_reviews.Freq), 0, n_reviews.Freq) + ifelse(is.na(n_reviews.comments), 0, n_reviews.comments)) %>% 
  select(-n_reviews.Freq, -n_reviews.comments)

# Build edge data
edges <- data.frame('from' = left_join(network.data_expanded,
                                       nodes,
                                       by = c('review_author' = 'auth')),
                    'to' = left_join(network.data_expanded,
                                     nodes,
                                     by = c('comment_author' = 'auth'))) %>% 
  select(from.id, to.id) %>% 
  distinct(from.id, to.id)

# Network visualization
net <- graph.data.frame(edges, 
                        nodes, 
                        directed = T)

net <- simplify(net, 
                remove.multiple = T, 
                remove.loops = F) 

# Define graphing params
V(net)$shape <- 'none'
V(net)$label <- V(net)$auth
V(net)$label.font <- 2
V(net)$label.color <- '#445359'
# V(net)$label.cex <- V(net)$t_interactions/100
E(net)$color <- '#f0f2f3'
E(net)$arrow.mode <- 0

# Define center node
center = which(nodes$t_interactions == max(nodes$t_interactions))

# Plot
plot(net, layout = layout.star(net, center = center))

```

```{r, stage-data}

## Find most active users and networks

# Remove reviews with less than 5 comments
network.data_active <- network.data[network.data$n_comment_authors > 20, ]

# Number of reviews by individual
n_reviews_active <- data.frame(table(network.data_active$author))

# Replicate review data based on the number of commenters
network.data_active_expanded <- data.frame('review_author' = rep(network.data_active$author, network.data_active$n_comment_authors), 
                           'comment_author' = unlist(network.data_active$comment_authors),
                           'product' = rep(network.data_active$product, network.data_active$n_comment_authors),
                           'brand' = rep(network.data_active$brand, network.data_active$n_comment_authors),
                           'type' = rep(network.data_active$type, network.data_active$n_comment_authors))

# Remove '@' from commenter names
network.data_active_expanded$comment_author <- gsub('@', '', network.data_active_expanded$comment_author)

# Number of comments
n_comments_active <- data.frame(table(network.data_active_expanded$comment_author))
names(n_comments_active) <- c('Var1', 'comments')

# Build column of review and comment authors
authors_total_expanded <- rbind(data.frame('auth' = network.data_expanded$review_author),
                       data.frame('auth' = network.data_expanded$comment_author))

authors_total_expanded <- data.frame('auth' = unique(gsub('@', '', authors_total_expanded$auth)))

authors_total_active <- data.frame('auth' = authors_total_expanded[authors_total_expanded$auth %in% n_reviews_active$Var1 | 
                                                            authors_total_expanded$auth %in% n_comments_active$Var1, ])

# Build node data
nodes_expanded <- data.frame('id' = paste0('c', seq(from = 1, to = nrow(authors_total_active))),
                    'name' = authors_total_active,
                    'n_reviews' = left_join(left_join(authors_total_active, 
                                            n_reviews,
                                            by = c('auth' = 'Var1')),
                                            n_comments,
                                            by = c('auth' = 'Var1'))) %>% 
  select(-n_reviews.auth) %>%
  mutate(t_interactions = ifelse(is.na(n_reviews.Freq), 0, n_reviews.Freq) + ifelse(is.na(n_reviews.comments), 0, n_reviews.comments)) %>% 
  select(-n_reviews.Freq, -n_reviews.comments)

# Build edge data
edges_expanded <- data.frame('from' = left_join(network.data_expanded,
                                       nodes_expanded,
                                       by = c('review_author' = 'auth')),
                    'to' = left_join(network.data_expanded,
                                     nodes_expanded,
                                     by = c('comment_author' = 'auth'))) %>% 
  select(from.id, to.id) %>% 
  distinct(from.id, to.id)

# Remove na rows
edges_expanded <- na.omit(edges_expanded)

# Add source and target author names
edges_expanded <- edges_expanded %>% 
  mutate('source' = left_join(edges_expanded,
                                 nodes_expanded,
                                 by = c('from.id' = 'id'))$auth,
         'target' = left_join(edges_expanded,
                                 nodes_expanded,
                                 by = c('to.id' = 'id'))$auth)

# write_csv(edges_expanded, 'links_active.csv')

```

```{r, sentiment-analysis}

```

